name: Update README weekly

on:
  schedule:
    - cron: '0 10 * * 1'  # Jeden Montag um 10:00 UTC
  workflow_dispatch:     # Optional: manuell auslösbar

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Zeitstempel ersetzen
        run: |
          # Neue Zeitzeile
          DATE="Zuletzt aktualisiert am: $(date -u)"
          
          # Falls Zeile schon existiert → ersetzen
          if grep -q "Zuletzt aktualisiert am:" README.md; then
            sed -i "s/Zuletzt aktualisiert am:.*/$DATE/" README.md
          else
            echo "$DATE" >> README.md
          fi

      - name: Änderungen committen & pushen
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "🕒 Zeitstempel aktualisiert: $(date -u)" || echo "Keine Änderungen"
          git push
